"use client";

import type { SyntheticEvent } from "react";
import { RotateCcw, Unlink, Link as LinkIcon } from "lucide-react";

import { MediaPicker } from "@/components/dashboard/online-store/MediaPicker";
import { CSS_UNITS, cssUnitToString, type BuilderBoxValues, type BuilderShadowValue, type BuilderStyleRules, type BuilderStyleState, type BuilderTransformValue, type CssNumericUnit, type CssUnitValue } from "@/lib/storefront-builder-style";

import { InspectorField, InspectorGroup, inspectorInputClass } from "./InspectorFields";

type StyleEditorProps = { rules: BuilderStyleRules; inherited: BuilderStyleRules; state: BuilderStyleState; onChange: (rules: BuilderStyleRules) => void; onClear: () => void };
const selectOptions = (values: string[]) => values.map((value) => <option key={value} value={value}>{value}</option>);

function UnitInput({ value, onChange, keywords = true }: { value: unknown; onChange: (value: CssUnitValue | undefined) => void; keywords?: boolean }) {
  const normalized = value && typeof value === "object" ? value as { value?: number | string; unit?: CssNumericUnit } : {};
  const keyword = typeof normalized.value === "string";
  const numericValue = typeof normalized.value === "number" && Number.isFinite(normalized.value) ? normalized.value : 0;
  return <div className="flex min-w-0 gap-1"><input type="number" disabled={keyword} value={keyword ? "" : numericValue} onChange={(event) => onChange({ value: Number(event.target.value), unit: normalized.unit || "px" })} className={`${inspectorInputClass} min-w-0 flex-1`} /><select aria-label="CSS unit" value={keyword ? normalized.value : normalized.unit || "px"} onChange={(event) => { const next = event.target.value; onChange(["auto", "min-content", "max-content", "fit-content"].includes(next) ? { value: next as "auto" } : { value: numericValue, unit: next as CssNumericUnit }); }} className="w-24 rounded-lg border border-[var(--color-brd)] bg-white px-2 text-xs">{CSS_UNITS.map((unit) => <option key={unit}>{unit}</option>)}{keywords ? <><option value="auto">auto</option><option value="min-content">min</option><option value="max-content">max</option><option value="fit-content">fit</option></> : null}</select>{value !== undefined ? <button type="button" title="Clear override" onClick={() => onChange(undefined)} className="rounded-lg border border-[var(--color-brd)] px-2"><RotateCcw size={12} /></button> : null}</div>;
}

function ColorControl({ value, onChange }: { value: unknown; onChange: (value: string | undefined) => void }) {
  const color = typeof value === "string" ? value : "";
  return <div className="flex gap-2"><input type="color" value={/^#[0-9a-f]{6}$/i.test(color) ? color : "#000000"} onChange={(event) => onChange(event.target.value)} className="h-10 w-12 rounded-lg border border-[var(--color-brd)]" /><input value={color} onChange={(event) => onChange(event.target.value || undefined)} placeholder="Theme token or color" className={inspectorInputClass} /></div>;
}

function SpacingControl({ value, onChange }: { value: unknown; onChange: (value: BuilderBoxValues) => void }) {
  const box = value && typeof value === "object" ? value as BuilderBoxValues : { linked: true };
  const linked = box.linked !== false;
  const sides = ["top", "right", "bottom", "left"] as const;
  function update(side: typeof sides[number], next: CssUnitValue | undefined) { onChange(linked ? { linked, top: next, right: next, bottom: next, left: next } : { ...box, linked, [side]: next }); }
  return <div className="space-y-2"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wide text-[var(--color-txt-sec)]">T · R · B · L</span><button type="button" aria-label={linked ? "Unlink spacing values" : "Link spacing values"} onClick={() => onChange({ ...box, linked: !linked })} className="rounded-md border border-[var(--color-brd)] p-1.5">{linked ? <LinkIcon size={12} /> : <Unlink size={12} />}</button></div><div className="grid gap-2">{sides.map((side) => <label key={side} className="grid grid-cols-[48px_1fr] items-center gap-2 text-xs capitalize"><span>{side}</span><UnitInput value={box[side]} onChange={(next) => update(side, next)} keywords={side === "top" || side === "bottom"} /></label>)}</div></div>;
}

function SelectField({ label, value, values, onChange }: { label: string; value: unknown; values: string[]; onChange: (value: string | undefined) => void }) { return <InspectorField label={label}><select value={String(value || "")} onChange={(event) => onChange(event.target.value || undefined)} className={inspectorInputClass}><option value="">Inherited/default</option>{selectOptions(values)}</select></InspectorField>; }

function CommitRange({ value, min, max, step, label, onCommit }: { value: number; min: number; max: number; step: number; label: string; onCommit: (value: number) => void }) {
  const commit = (event: SyntheticEvent<HTMLInputElement>) => { const next = Number(event.currentTarget.value); if (next !== value) onCommit(next); };
  return <input key={value} aria-label={label} type="range" min={min} max={max} step={step} defaultValue={value} onPointerUp={commit} onKeyUp={commit} onBlur={commit} className="w-full" />;
}

export function AdvancedStyleInspector({ rules, inherited, state, onChange, onClear }: StyleEditorProps) {
  const set = (key: string, value: unknown) => { const next = { ...rules }; if (value === undefined || value === "") delete next[key]; else next[key] = value; onChange(next); };
  const unit = (key: string, label: string, keywords = true) => <InspectorField label={label}><UnitInput value={rules[key]} onChange={(value) => set(key, value)} keywords={keywords} />{rules[key] === undefined && inherited[key] !== undefined ? <p className="mt-1 text-[10px] text-[var(--color-txt-sec)]">Inherited · {cssUnitToString(inherited[key]) || String(inherited[key])}</p> : null}</InspectorField>;
  const display = String(rules.display || inherited.display || "block");
  const backgroundType = rules.backgroundImageValue ? "image" : rules.backgroundGradient ? "gradient" : "solid";
  const shadow = (rules.shadow || {}) as BuilderShadowValue;
  const transform = (rules.transformValue || {}) as BuilderTransformValue;
  return <>
    <InspectorGroup title={`Layout · ${state === "base" ? "Normal" : "Hover"}`}>
      <SelectField label="Display" value={rules.display} values={["block", "flex", "grid", "inline-flex", "none"]} onChange={(value) => set("display", value)} />
      {display.includes("flex") ? <><SelectField label="Direction" value={rules.flexDirection} values={["row", "column", "row-reverse", "column-reverse"]} onChange={(value) => set("flexDirection", value)} /><SelectField label="Wrap" value={rules.flexWrap} values={["nowrap", "wrap", "wrap-reverse"]} onChange={(value) => set("flexWrap", value)} /><SelectField label="Justify" value={rules.justifyContent} values={["flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly"]} onChange={(value) => set("justifyContent", value)} /><SelectField label="Align items" value={rules.alignItems} values={["stretch", "flex-start", "center", "flex-end", "baseline"]} onChange={(value) => set("alignItems", value)} /></> : null}
      {display === "grid" ? <InspectorField label="Columns"><input type="number" min={1} max={12} value={Number(rules.gridColumns || 1)} onChange={(event) => { const count = Math.max(1, Math.min(12, Number(event.target.value))); onChange({ ...rules, gridColumns: count, gridTemplateColumns: `repeat(${count}, minmax(0, 1fr))` }); }} className={inspectorInputClass} /></InspectorField> : null}
      {(display.includes("flex") || display === "grid") ? <>{unit("gap", "Gap", false)}{unit("rowGap", "Row gap", false)}{unit("columnGap", "Column gap", false)}</> : null}
    </InspectorGroup>
    <InspectorGroup title="Size">{unit("width", "Width")}{unit("minWidth", "Min width")}{unit("maxWidth", "Max width")}{unit("height", "Height")}{unit("minHeight", "Min height")}{unit("maxHeight", "Max height")}<InspectorField label="Aspect ratio"><input value={String(rules.aspectRatio || "")} onChange={(event) => set("aspectRatio", event.target.value)} placeholder="16 / 9" className={inspectorInputClass} /></InspectorField><div className="grid grid-cols-3 gap-2"><InspectorField label="Grow"><input type="number" value={Number(rules.flexGrow || 0)} onChange={(event) => set("flexGrow", Number(event.target.value))} className={inspectorInputClass} /></InspectorField><InspectorField label="Shrink"><input type="number" value={Number(rules.flexShrink ?? 1)} onChange={(event) => set("flexShrink", Number(event.target.value))} className={inspectorInputClass} /></InspectorField><InspectorField label="Basis"><UnitInput value={rules.flexBasis} onChange={(value) => set("flexBasis", value)} /></InspectorField></div></InspectorGroup>
    <InspectorGroup title="Spacing"><InspectorField label="Margin"><SpacingControl value={rules.margin} onChange={(value) => set("margin", value)} /></InspectorField><InspectorField label="Padding"><SpacingControl value={rules.padding} onChange={(value) => set("padding", value)} /></InspectorField></InspectorGroup>
    <InspectorGroup title="Typography"><SelectField label="Font preset/family" value={rules.fontFamily} values={["inherit", "var(--font-sans)", "system-ui", "Georgia, serif", "ui-monospace, monospace"]} onChange={(value) => set("fontFamily", value)} />{unit("fontSize", "Font size", false)}<InspectorField label="Weight"><input type="number" min={100} max={900} step={100} value={Number(rules.fontWeight || 400)} onChange={(event) => set("fontWeight", Number(event.target.value))} className={inspectorInputClass} /></InspectorField><SelectField label="Style" value={rules.fontStyle} values={["normal", "italic", "oblique"]} onChange={(value) => set("fontStyle", value)} />{unit("lineHeight", "Line height", false)}{unit("letterSpacing", "Letter spacing", false)}<SelectField label="Text align" value={rules.textAlign} values={["left", "center", "right", "justify"]} onChange={(value) => set("textAlign", value)} /><SelectField label="Transform" value={rules.textTransform} values={["none", "uppercase", "lowercase", "capitalize"]} onChange={(value) => set("textTransform", value)} /><SelectField label="Decoration" value={rules.textDecoration} values={["none", "underline", "overline", "line-through"]} onChange={(value) => set("textDecoration", value)} /><SelectField label="White space" value={rules.whiteSpace} values={["normal", "nowrap", "pre-wrap", "break-spaces"]} onChange={(value) => set("whiteSpace", value)} /><InspectorField label="Text color"><ColorControl value={rules.color} onChange={(value) => set("color", value)} /></InspectorField></InspectorGroup>
    <InspectorGroup title="Background"><SelectField label="Type" value={backgroundType} values={["solid", "gradient", "image"]} onChange={(value) => { if (value !== "gradient") set("backgroundGradient", undefined); if (value !== "image") set("backgroundImageValue", undefined); }} />{backgroundType === "solid" ? <InspectorField label="Color"><ColorControl value={rules.backgroundColor} onChange={(value) => set("backgroundColor", value)} /></InspectorField> : null}{backgroundType === "gradient" ? <><SelectField label="Gradient" value={(rules.backgroundGradient as { type?: string })?.type} values={["linear", "radial"]} onChange={(value) => set("backgroundGradient", { ...(rules.backgroundGradient as object || {}), type: value || "linear" })} /><InspectorField label="Start / End"><div className="grid grid-cols-2 gap-2"><ColorControl value={(rules.backgroundGradient as { from?: string })?.from} onChange={(value) => set("backgroundGradient", { ...(rules.backgroundGradient as object || {}), from: value })} /><ColorControl value={(rules.backgroundGradient as { to?: string })?.to} onChange={(value) => set("backgroundGradient", { ...(rules.backgroundGradient as object || {}), to: value })} /></div></InspectorField></> : null}{backgroundType === "image" ? <><MediaPicker label="Background image" mediaType="section" value={String((rules.backgroundImageValue as { url?: string })?.url || "")} onChange={(url) => set("backgroundImageValue", { ...(rules.backgroundImageValue as object || {}), url })} /><SelectField label="Size" value={(rules.backgroundImageValue as { size?: string })?.size} values={["cover", "contain", "auto"]} onChange={(size) => set("backgroundImageValue", { ...(rules.backgroundImageValue as object || {}), size })} /><SelectField label="Position" value={(rules.backgroundImageValue as { position?: string })?.position} values={["center", "top", "bottom", "left", "right"]} onChange={(position) => set("backgroundImageValue", { ...(rules.backgroundImageValue as object || {}), position })} /></> : null}<InspectorField label="Overlay"><div className="space-y-2"><ColorControl value={(rules.backgroundOverlay as { color?: string })?.color} onChange={(color) => set("backgroundOverlay", color ? { ...(rules.backgroundOverlay as object || {}), color, opacity: Number((rules.backgroundOverlay as { opacity?: number })?.opacity ?? 0.4) } : undefined)} />{rules.backgroundOverlay ? <input aria-label="Background overlay opacity" type="range" min={0} max={1} step={0.05} value={Number((rules.backgroundOverlay as { opacity?: number }).opacity ?? 0.4)} onChange={(event) => set("backgroundOverlay", { ...(rules.backgroundOverlay as object || {}), opacity: Number(event.target.value) })} className="w-full" /> : null}</div></InspectorField></InspectorGroup>
    <InspectorGroup title="Border"><InspectorField label="Width"><UnitInput value={rules.borderWidth} onChange={(value) => set("borderWidth", value)} keywords={false} /></InspectorField><details><summary className="cursor-pointer text-xs font-semibold">Independent sides</summary><div className="mt-2 grid grid-cols-2 gap-2">{[["borderTopWidth", "Top"], ["borderRightWidth", "Right"], ["borderBottomWidth", "Bottom"], ["borderLeftWidth", "Left"]].map(([key, label]) => <InspectorField key={key} label={label}><UnitInput value={rules[key]} onChange={(value) => set(key, value)} keywords={false} /></InspectorField>)}</div></details><SelectField label="Style" value={rules.borderStyle} values={["none", "solid", "dashed", "dotted", "double"]} onChange={(value) => set("borderStyle", value)} /><InspectorField label="Color"><ColorControl value={rules.borderColor} onChange={(value) => set("borderColor", value)} /></InspectorField><InspectorField label="Radius"><UnitInput value={rules.borderRadius} onChange={(value) => set("borderRadius", value)} keywords={false} /></InspectorField><details><summary className="cursor-pointer text-xs font-semibold">Independent corners</summary><div className="mt-2 grid grid-cols-2 gap-2">{[["borderTopLeftRadius", "Top left"], ["borderTopRightRadius", "Top right"], ["borderBottomRightRadius", "Bottom right"], ["borderBottomLeftRadius", "Bottom left"]].map(([key, label]) => <InspectorField key={key} label={label}><UnitInput value={rules[key]} onChange={(value) => set(key, value)} keywords={false} /></InspectorField>)}</div></details></InspectorGroup>
    <InspectorGroup title="Effects"><InspectorField label="Opacity"><CommitRange label="Opacity" min={0} max={1} step={0.01} value={Number(rules.opacity ?? 1)} onCommit={(value) => set("opacity", value)} /><span className="text-xs">{Math.round(Number(rules.opacity ?? 1) * 100)}%</span></InspectorField><InspectorField label="Box shadow"><div className="grid grid-cols-4 gap-2">{(["x", "y", "blur", "spread"] as const).map((key) => <input key={key} title={key} type="number" value={Number(shadow[key] || 0)} onChange={(event) => set("shadow", { ...shadow, [key]: Number(event.target.value) })} className={inspectorInputClass} />)}</div><ColorControl value={shadow.color} onChange={(color) => set("shadow", { ...shadow, color })} /></InspectorField><InspectorField label="Filters"><div className="grid grid-cols-2 gap-2">{["blur", "brightness", "contrast", "grayscale", "saturate"].map((key) => <label key={key} className="text-[10px] capitalize">{key}<input type="number" value={Number((rules.filters as Record<string, unknown> | undefined)?.[key] ?? (key === "blur" || key === "grayscale" ? 0 : 100))} onChange={(event) => set("filters", { ...(rules.filters as object || {}), [key]: Number(event.target.value) })} className={inspectorInputClass} /></label>)}</div></InspectorField></InspectorGroup>
    <InspectorGroup title="Position"><SelectField label="Position" value={rules.position} values={["static", "relative", "absolute", "fixed", "sticky"]} onChange={(value) => set("position", value)} />{["absolute", "fixed"].includes(String(rules.position)) ? <p className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">Advanced positioning removes this element from the normal document flow.</p> : null}{rules.position && rules.position !== "static" ? <div className="grid grid-cols-2 gap-2">{["top", "right", "bottom", "left"].map((key) => <InspectorField key={key} label={key}><UnitInput value={rules[key]} onChange={(value) => set(key, value)} /></InspectorField>)}</div> : null}<InspectorField label="Z-index"><input type="number" value={Number(rules.zIndex || 0)} onChange={(event) => set("zIndex", Number(event.target.value))} className={inspectorInputClass} /></InspectorField><SelectField label="Overflow" value={rules.overflow} values={["visible", "hidden", "auto", "scroll", "clip"]} onChange={(value) => set("overflow", value)} /><div className="grid grid-cols-2 gap-2"><SelectField label="Overflow X" value={rules.overflowX} values={["visible", "hidden", "auto", "scroll", "clip"]} onChange={(value) => set("overflowX", value)} /><SelectField label="Overflow Y" value={rules.overflowY} values={["visible", "hidden", "auto", "scroll", "clip"]} onChange={(value) => set("overflowY", value)} /></div></InspectorGroup>
    <InspectorGroup title="Transform"><div className="grid grid-cols-2 gap-2"><InspectorField label="Translate X"><UnitInput value={transform.translateX} onChange={(value) => set("transformValue", { ...transform, translateX: value })} /></InspectorField><InspectorField label="Translate Y"><UnitInput value={transform.translateY} onChange={(value) => set("transformValue", { ...transform, translateY: value })} /></InspectorField><InspectorField label="Rotate"><input type="number" value={Number(transform.rotate || 0)} onChange={(event) => set("transformValue", { ...transform, rotate: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField><InspectorField label="Scale"><input type="number" step={0.05} value={Number(transform.scaleX ?? 1)} onChange={(event) => set("transformValue", { ...transform, scaleX: Number(event.target.value), scaleY: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField><InspectorField label="Skew X"><input type="number" value={Number(transform.skewX || 0)} onChange={(event) => set("transformValue", { ...transform, skewX: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField><InspectorField label="Skew Y"><input type="number" value={Number(transform.skewY || 0)} onChange={(event) => set("transformValue", { ...transform, skewY: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField></div><InspectorField label="Transform origin"><input value={String(transform.origin || "center")} onChange={(event) => set("transformValue", { ...transform, origin: event.target.value })} className={inspectorInputClass} /></InspectorField><div className="grid grid-cols-3 gap-2"><InspectorField label="Duration"><input type="number" min={0} value={Number((rules.transitionValue as { duration?: number })?.duration ?? 200)} onChange={(event) => set("transitionValue", { ...(rules.transitionValue as object || {}), duration: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField><InspectorField label="Easing"><select value={String((rules.transitionValue as { easing?: string })?.easing || "ease")} onChange={(event) => set("transitionValue", { ...(rules.transitionValue as object || {}), easing: event.target.value })} className={inspectorInputClass}>{selectOptions(["ease", "linear", "ease-in", "ease-out", "ease-in-out"])}</select></InspectorField><InspectorField label="Delay"><input type="number" min={0} value={Number((rules.transitionValue as { delay?: number })?.delay ?? 0)} onChange={(event) => set("transitionValue", { ...(rules.transitionValue as object || {}), delay: Number(event.target.value) })} className={inspectorInputClass} /></InspectorField></div></InspectorGroup>
    <InspectorGroup title="Responsive visibility"><div className="grid grid-cols-2 gap-2"><SelectField label="Visibility" value={rules.visibility} values={["visible", "hidden"]} onChange={(value) => set("visibility", value)} /><SelectField label="Display" value={rules.display} values={["block", "flex", "grid", "none"]} onChange={(value) => set("display", value)} /></div></InspectorGroup>
    <div className="border-t border-[var(--color-brd)] p-4"><button type="button" onClick={onClear} className="flex w-full items-center justify-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700"><RotateCcw size={13} /> Reset {state === "base" ? "node styles" : "hover styles"}</button></div>
  </>;
}

export { ColorControl, SpacingControl, UnitInput };
