"use client";
import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { MediaPicker } from "@/components/dashboard/online-store/MediaPicker";
import { api, ApiError } from "@/lib/api";

export type CustomFieldDefinition = { id: string; namespace: string; key: string; name: string; description?: string | null; owner_type: string; value_type: string; validation: Record<string, unknown>; is_required: boolean; is_public: boolean };
type FieldValue = { definition_id: string; value: unknown }; type ContentModel = { id: string; key: string; name: string }; type ContentEntry = { id: string; handle: string; values: Record<string, unknown> };

export function CustomFieldsEditor({ ownerType, ownerId }: { ownerType: "product" | "product_variant" | "collection" | "page"; ownerId: string }) {
  const [definitions, setDefinitions] = useState<CustomFieldDefinition[]>([]); const [values, setValues] = useState<Record<string, unknown>>({}); const [entries, setEntries] = useState<Record<string, ContentEntry[]>>({}); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; Promise.all([api.get<CustomFieldDefinition[]>(`/admin/storefront/custom-fields?owner_type=${ownerType}`), api.get<FieldValue[]>(`/admin/storefront/custom-field-values/${ownerType}/${ownerId}`), api.get<ContentModel[]>("/admin/storefront/content-models")]).then(async ([defs, stored, models]) => { const pairs = await Promise.all(models.map(async (model) => [model.key, await api.get<ContentEntry[]>(`/admin/storefront/content-models/${model.id}/entries`)] as const)); if (active) { setDefinitions(defs); setValues(Object.fromEntries(stored.map((item) => [item.definition_id, item.value]))); setEntries(Object.fromEntries(pairs)); } }).catch((caught) => { if (active) setError(caught instanceof ApiError ? caught.message : "Could not load custom fields."); }); return () => { active = false; }; }, [ownerId, ownerType]);
  if (!definitions.length && !error) return null;
  async function save() { setSaving(true); setError(""); try { await api.put(`/admin/storefront/custom-field-values/${ownerType}/${ownerId}`, definitions.map((definition) => ({ definition_id: definition.id, value: values[definition.id] ?? null }))); setMessage("Custom fields saved."); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Could not save custom fields."); } finally { setSaving(false); } }
  return <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-700">Dynamic data</p><h2 className="mt-1 text-xl font-bold">Custom fields</h2><p className="mt-1 text-sm text-slate-500">Stable field keys can be bound in storefront templates.</p></div><button type="button" disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Save size={15}/>{saving ? "Saving…" : "Save fields"}</button></div>{error ? <p className="mt-3 text-sm text-rose-700">{error}</p> : null}{message ? <p className="mt-3 text-sm text-emerald-700">{message}</p> : null}<div className="mt-5 grid gap-4 md:grid-cols-2">{definitions.map((definition) => <Field key={definition.id} definition={definition} value={values[definition.id]} entries={entries} onChange={(value) => setValues((current) => ({ ...current, [definition.id]: value }))}/>)}</div></section>;
}
function Field({ definition, value, entries, onChange }: { definition: CustomFieldDefinition; value: unknown; entries: Record<string, ContentEntry[]>; onChange: (value: unknown) => void }) {
  const label = <span className="mb-2 block text-sm font-semibold text-slate-800">{definition.name}{definition.is_required ? " *" : ""}<small className="ml-2 font-mono text-[10px] text-slate-400">{definition.namespace}.{definition.key}</small></span>; const inputClass = "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-violet-400";
  if (definition.value_type === "image") return <div className="md:col-span-2"><MediaPicker label={definition.name} mediaType="section" value={String(value || "")} onChange={onChange}/></div>;
  if (definition.value_type === "boolean") return <label className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-semibold"><input type="checkbox" checked={value === true} onChange={(event) => onChange(event.target.checked)}/>{definition.name}</label>;
  if (definition.value_type === "multiline_text") return <label className="md:col-span-2">{label}<textarea className={`${inputClass} min-h-28`} value={String(value || "")} onChange={(event) => onChange(event.target.value)}/></label>;
  if (definition.value_type === "reference") { const modelKey = String(definition.validation.reference_model_key || ""); return <label>{label}<select className={inputClass} value={value && typeof value === "object" ? String((value as { entry_handle?: unknown }).entry_handle || "") : ""} onChange={(event) => onChange(event.target.value ? { model_key: modelKey, entry_handle: event.target.value } : null)}><option value="">No entry</option>{(entries[modelKey] || []).map((entry) => <option key={entry.id} value={entry.handle}>{String(entry.values.name || entry.handle)}</option>)}</select></label>; }
  const type = definition.value_type === "date" ? "date" : ["integer", "decimal", "money"].includes(definition.value_type) ? "number" : definition.value_type === "color" ? "color" : definition.value_type === "url" ? "url" : "text";
  return <label>{label}<input type={type} className={inputClass} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)}/>{definition.description ? <span className="mt-1 block text-xs text-slate-500">{definition.description}</span> : null}</label>;
}
